
CREATE TABLE Productos (
ID_PRODUCTO VARCHAR(5) PRIMARY KEY NOT NULL,
PRODUCTO VARCHAR(40) NOT NULL,
PRECIO VARCHAR(6) NOT NULL,
EXISTENCIAS VARCHAR(4) NOT NULL
);

CREATE TABLE Tickets (
FECHA VARCHAR(20) PRIMARY KEY NOT NULL,
HORA_VENTA VARCHAR(5) NOT NULL,
CANTIDAD_PRODUCTO VARCHAR(4) NOT NULL,
PRODUCTO VARCHAR(40) NOT NULL,
TOTAL_PRODUCTO VARCHAR(6) NOT NULL
);
