
CREATE TABLE Productos (
ID_PRODUCTO VARCHAR(5) PRIMARY KEY NOT NULL,
PRODUCTO VARCHAR(40) NOT NULL,
PRECIO VARCHAR(6) NOT NULL,
EXISTENCIAS VARCHAR(4) NOT NULL
);

CREATE TABLE Tickets (
ID_TICKET VARCHAR (5) PRIMARY KEY NOT NULL,
FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CANTIDAD_PRODUCTO VARCHAR(4) NOT NULL,
PRODUCTO VARCHAR(40) NOT NULL,
TOTAL_PRODUCTO VARCHAR(6) NOT NULL
);

INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P001", "CR7 Drive", "563", "8" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P002", "Caja de barras de proteina sabor chocolate", "800", "8" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P003", "Polvo para malteada sabor coco", "1248", "10" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P004", "Te verde sabor granada", "304", "9" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P005", "Te concentrado de hierbas", "310", "10" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P006", "Proteina Stregth", "1200", "9" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P007", "Herbalife Formula Numero 1", "1100", "10" );
INSERT INTO Productos(ID_PRODUCTO, PRODUCTO, PRECIO, EXISTENCIAS) values("P008", "Fibra Natural Sabor Manzana", "720", "10" );

INSERT INTO Tickets(ID_TICKET, CANTIDAD_PRODUCTO, PRODUCTO, TOTAL_PRODUCTO) values("T001", "2", "Caja de barras de proteina sabor chocolate", "1600");
INSERT INTO Tickets(ID_TICKET, CANTIDAD_PRODUCTO, PRODUCTO, TOTAL_PRODUCTO) values("T002", "1", "Proteina Strength", "1200");